### ISSUE TITLE
Does not work in QGIS 2.6

### ISSUE THREAD

**Issue by tillnagel** [dgoedkoop/joinmultiplelines#5]
I have multiple line features selected, but nothing happens when trying to run the plugin. No error message, no result, nothing.

Also, I am not able to open the test data from your repository.

**Comment by tillnagel** [comment]
The plugin seems to be installed correctly. I get the appropriate error messages (e.g. when only one line feature is selected). 

Maybe it's just a user error: What should happen after successful join operation? Where do I find the new feature?

**Comment by dgoedkoop** [comment]
The old features should be replaced by the new feature, which will also be selected. So on success, it will look like nothing has happened, but if you use the selection tool you will notice that the selection now consists of only the one single joined line.

If it really does not work, without any error message, could you provide a small data sample to test?

**Comment by tillnagel** [comment]
Ok, got it. I tried it with GML files, but it only works if the loaded file type is a Shapefile. Then, your plugin works as expected.
